version: "3"
services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - "${MYSQL_DIR}/db:/var/lib/mysql"
      - "${MYSQL_DIR}/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
  wordpress:
    depends_on:
      - db
    build: "${BLOG_DIR}"
    container_name: wordpress
    ports:
      - "${SERVER_PORT}:80"
    restart: always
    volumes:
      - "${BLOG_DIR}/wordpress:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: "db:${MYSQL_PORT}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
